### ISSUE TITLE
spark dataframe write data to starrocks error !!!

### ISSUE THREAD

**Issue by zyfbbd** [gaoy121/starrocks-connector-for-apache-spark#5]
spark构建dataframe利用【starrocks-spark3_2.12-1.0.1.jar】http stream方式向starrocks导入数据

dataset.repartition(numPartition).write().format("starrocks")
                    .option("starrocks.benodes", StarRocks_BE_NODE)
                    .option("starrocks.table.identifier", Sink_Table)
                    .option("user", StarRocks_USER)
                    .option("password", StarRocks_PASS)
                    .save();

出现以下异常提示：
java.io.IOException: Failed to load 10000 batch data on BE: http://x.x.x.x:8040/api/app_backend/store_street_info/_stream_load? node and exceeded the max 1 retry times.
	at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$4(StarrocksSourceProvider.scala:128)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at com.starrocks.connector.spark.sql.StarrocksSourceProvider.flush$1(StarrocksSourceProvider.scala:102)
	at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$1(StarrocksSourceProvider.scala:92)
	at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$1$adapted(StarrocksSourceProvider.scala:77)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011)
	at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011)
	at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:136)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: com.starrocks.connector.spark.exception.StreamLoadException: stream load error: http request exception,load url : http://x.x.x.x:8040/api/app_backend/store_street_info/_stream_load?,failed to execute spark streamload with label: spark_streamload_20230522_112359_445f68d7fe8c49a185e3f342f5f9faa8
	at com.starrocks.connector.spark.StarRocksStreamLoad.load(StarRocksStreamLoad.java:204)
	at com.starrocks.connector.spark.StarRocksStreamLoad.loadV2(StarRocksStreamLoad.java:196)
	at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$5(StarrocksSourceProvider.scala:106)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$4(StarrocksSourceProvider.scala:104)
	... 15 more

**Comment by gaoy121** [comment]
> spark构建dataframe利用【starrocks-spark3_2.12-1.0.1.jar】http stream方式向starrocks导入数据
> 
> dataset.repartition(numPartition).write().format("starrocks") .option("starrocks.benodes", StarRocks_BE_NODE) .option("starrocks.table.identifier", Sink_Table) .option("user", StarRocks_USER) .option("password", StarRocks_PASS) .save();
> 
> 出现以下异常提示： java.io.IOException: Failed to load 10000 batch data on BE: http://x.x.x.x:8040/api/app_backend/store_street_info/_stream_load? node and exceeded the max 1 retry times. at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$4(StarrocksSourceProvider.scala:128) at scala.util.control.Breaks.breakable(Breaks.scala:42) at com.starrocks.connector.spark.sql.StarrocksSourceProvider.flush$1(StarrocksSourceProvider.scala:102) at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$1(StarrocksSourceProvider.scala:92) at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$1$adapted(StarrocksSourceProvider.scala:77) at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2(RDD.scala:1011) at org.apache.spark.rdd.RDD.$anonfun$foreachPartition$2$adapted(RDD.scala:1011) at org.apache.spark.SparkContext.$anonfun$runJob$5(SparkContext.scala:2268) at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90) at org.apache.spark.scheduler.Task.run(Task.scala:136) at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:548) at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1504) at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:551) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) at java.lang.Thread.run(Thread.java:750) Caused by: com.starrocks.connector.spark.exception.StreamLoadException: stream load error: http request exception,load url : http://x.x.x.x:8040/api/app_backend/store_street_info/_stream_load?,failed to execute spark streamload with label: spark_streamload_20230522_112359_445f68d7fe8c49a185e3f342f5f9faa8 at com.starrocks.connector.spark.StarRocksStreamLoad.load(StarRocksStreamLoad.java:204) at com.starrocks.connector.spark.StarRocksStreamLoad.loadV2(StarRocksStreamLoad.java:196) at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$5(StarrocksSourceProvider.scala:106) at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158) at com.starrocks.connector.spark.sql.StarrocksSourceProvider.$anonfun$createRelation$4(StarrocksSourceProvider.scala:104) ... 15 more

StarRocks使用的哪个版本呢
